# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2951ad172590fdc0d225a3bdd6c84a165ff06603fc1da19e11291c927940b66d38382245de6ac8201d8ac8e1486b5e3df8c4481967d5a1c21fa2c91caa853011

test:
  secret_key_base: 233c1a6b420fa5ee44d69437053bdfb357b4fcebdd4a60164c63f6ce479d9c4f5fd739947d3dd96a41b5aef7be61d73d9862a16c5eeba9fd2ad581d58a0bb95b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
